--- 
# Install aws cli
- hosts: localhost 
  become: true
 
  tasks:
  - name: run ansible playbook locally
    debug:
    msg: "Hi This Is DecodingDevOps"

  tasks:
  - name: Install curl
    apt:
      name:
      - curl
      - unzip
      state: latest
 
  tasks:
  - name: Download aws-cli.zip
    get_url:
      url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
      dest: ./awscliv2.zip
      mode: 0755 
 
#  tasks:
#  - name: unzip aws-cli.zip
#    unarchive:
#      src: awscliv2.zip
#      dest: ./
  

      