--- # Install aws cli
  - name: Install curl
    apt:
      - curl
      - unzip
    state: latest
    cache_valid_time: 3600
  - name: "Install aws-cli"
    hosts: localhost
    connection: local 
    tasks:
    - name: "just execute a ls -lrt command"
      shell: "ls -lrt"
      register: "output"
    - debug: var=output.stdout_lines