--- # Install aws cli
- hosts: localhost
  connection: local 
  become: true
  tasks:
  - name: Install curl
    apt:
      name:
      - curl
      - unzip
      state: latest
  task:
  - name: Download aws-cli.zip
    get_url:
      url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
      dest: awscliv2.zip
      mode: '0440'

