--- 
# Install aws cli
- hosts: localhost 
  become: true
 
  tasks:
  - name: "Update Repository cache"
    apt:
      update_cache: true
      cache_valid_time: 3600
      force_apt_get: true

  tasks:
  - name: run ansible playbook locally
    debug:
    msg: "Hi This Is DecodingDevOps"

  tasks:
  - name: Install curl
    apt:
      name:
      - curl
      - unzip
      state: latest
 
  tasks:
  - name: update Repository
    apt:
      name: aws-cli
      state: presentd
      
  

      