--- # Install aws cli
  - name: Install curl
    ansible.builtin.apt:
      name: curl
      state: present
  - name: "Install aws-cli"
    hosts: localhost
    connection: local 
    tasks:
    - name: "just execute a ls -lrt command"
      shell: "ls -lrt"
      register: "output"
    - debug: var=output.stdout_lines