--- 
# Install tools k8s
- hosts: localhost 
  become: true
  tasks:
    - block:
       - name: Display log 
         debug:
           msg: "*** Start install k8s tools ***"
       - name: "Update Repository cache"
         apt:
            update_cache: true
            cache_valid_time: 3600
            force_apt_get: true
       - name: Install snap
         apt:
            name:
            - snap
            state: latest
       - name: Install kubectl
         snap:
            name:
            - kubectl
            classic: true
            state: present
      rescue:
        - name: Display error 
          debug:
            msg: "Install failed."







  

      